// GENERATED FILE — DO NOT EDIT BY HAND.
//
// Written by `scripts/generate-cli-routes.mjs` from the route tree under
// `src/app/api`. Run `npm run generate:cli-routes` after adding, moving or
// removing a route; `npm run check:cli-routes` fails in CI when this file
// and the route tree disagree, which is what keeps it honest.
//
// This is how the command line's `http` binding addresses each operation.
// It replaced 68 hand-written `RouteSpec` entries across eight files, which
// were a second copy of facts the routes already declared. See the generator
// for why the unwrap key is declared there rather than inferred here.

/** How one operation is addressed over HTTP. */
export interface GeneratedRoute {
  readonly method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  /** The URL template, with `{param}` for each path parameter. */
  readonly path: string;
  /** Which operation input field each path parameter carries. */
  readonly pathFields: Readonly<Record<string, string>>;
  /**
   * Input fields a body-carrying route reads from the QUERY STRING instead.
   *
   * Keyed by input field, valued by the query parameter's spelling —
   * `transition_item`'s `dryRun` travels as `?dry_run=`. Sending one of
   * these in the body means the route never sees it, which for a rehearsal
   * flag turns a dry run into a real move.
   */
  readonly queryFields: Readonly<Record<string, string>>;
  /** Whether the route reads a request body. */
  readonly sendsBody: boolean;
  /** The response key holding the result, or `null` when the body is it. */
  readonly unwrapKey: string | null;
}

/** Every operation the web API serves, by the name the service knows it as. */
export const GENERATED_ROUTES: Readonly<Record<string, GeneratedRoute>> = Object.freeze({
  accept_run_score: {
    method: "POST",
    path: "/api/runs/{id}/accept",
    pathFields: { id: "runId" },
    queryFields: {},
    sendsBody: true,
    unwrapKey: null,
  },
  backfill: {
    method: "POST",
    path: "/api/backfill",
    pathFields: {},
    queryFields: {},
    sendsBody: true,
    unwrapKey: null,
  },
  checkpoint: {
    method: "POST",
    path: "/api/checkpoints",
    pathFields: {},
    queryFields: {},
    sendsBody: true,
    unwrapKey: "event",
  },
  claim: {
    method: "POST",
    path: "/api/claims",
    pathFields: {},
    queryFields: {},
    sendsBody: true,
    unwrapKey: "assignment",
  },
  clear_intervention_level: {
    method: "DELETE",
    path: "/api/interventions/{id}/level",
    pathFields: { id: "id" },
    queryFields: {},
    sendsBody: false,
    unwrapKey: null,
  },
  complete_item: {
    method: "POST",
    path: "/api/items/{id}/complete",
    pathFields: { id: "id" },
    queryFields: {},
    sendsBody: true,
    unwrapKey: "item",
  },
  create_area: {
    method: "POST",
    path: "/api/areas",
    pathFields: {},
    queryFields: {},
    sendsBody: true,
    unwrapKey: "area",
  },
  create_item: {
    method: "POST",
    path: "/api/items",
    pathFields: {},
    queryFields: {},
    sendsBody: true,
    unwrapKey: "item",
  },
  create_project: {
    method: "POST",
    path: "/api/projects",
    pathFields: {},
    queryFields: {},
    sendsBody: true,
    unwrapKey: "item",
  },
  create_repo: {
    method: "POST",
    path: "/api/repos",
    pathFields: {},
    queryFields: {},
    sendsBody: true,
    unwrapKey: "repo",
  },
  create_subtask: {
    method: "POST",
    path: "/api/subtasks",
    pathFields: {},
    queryFields: {},
    sendsBody: true,
    unwrapKey: "item",
  },
  create_task: {
    method: "POST",
    path: "/api/tasks",
    pathFields: {},
    queryFields: {},
    sendsBody: true,
    unwrapKey: "item",
  },
  delete_area: {
    method: "DELETE",
    path: "/api/areas/{id}",
    pathFields: { id: "id" },
    queryFields: {},
    sendsBody: true,
    unwrapKey: null,
  },
  delete_item: {
    method: "DELETE",
    path: "/api/items/{id}",
    pathFields: { id: "id" },
    queryFields: {},
    sendsBody: true,
    unwrapKey: null,
  },
  delete_person: {
    method: "DELETE",
    path: "/api/people/{id}",
    pathFields: { id: "id" },
    queryFields: {},
    sendsBody: true,
    unwrapKey: null,
  },
  delete_repo: {
    method: "DELETE",
    path: "/api/repos/{id}",
    pathFields: { id: "id" },
    queryFields: {},
    sendsBody: true,
    unwrapKey: null,
  },
  delete_setting: {
    method: "DELETE",
    path: "/api/settings/{key}",
    pathFields: { key: "key" },
    queryFields: {},
    sendsBody: false,
    unwrapKey: null,
  },
  derive_run_score: {
    method: "POST",
    path: "/api/runs/{id}/derive",
    pathFields: { id: "runId" },
    queryFields: {},
    sendsBody: true,
    unwrapKey: null,
  },
  get_account: {
    method: "GET",
    path: "/api/accounts/{id}",
    pathFields: { id: "id" },
    queryFields: {},
    sendsBody: false,
    unwrapKey: "account",
  },
  get_activity: {
    method: "GET",
    path: "/api/activity",
    pathFields: {},
    queryFields: {},
    sendsBody: false,
    unwrapKey: null,
  },
  get_area: {
    method: "GET",
    path: "/api/areas/{id}",
    pathFields: { id: "id" },
    queryFields: {},
    sendsBody: false,
    unwrapKey: "area",
  },
  get_board: {
    method: "GET",
    path: "/api/board",
    pathFields: {},
    queryFields: {},
    sendsBody: false,
    unwrapKey: "board",
  },
  get_costs: {
    method: "GET",
    path: "/api/costs",
    pathFields: {},
    queryFields: {},
    sendsBody: false,
    unwrapKey: null,
  },
  get_crew_name: {
    method: "POST",
    path: "/api/crew/name",
    pathFields: {},
    queryFields: {},
    sendsBody: true,
    unwrapKey: "name",
  },
  get_events: {
    method: "GET",
    path: "/api/events",
    pathFields: {},
    queryFields: {},
    sendsBody: false,
    unwrapKey: null,
  },
  get_fleet: {
    method: "GET",
    path: "/api/fleet",
    pathFields: {},
    queryFields: {},
    sendsBody: false,
    unwrapKey: null,
  },
  get_intervention_scores: {
    method: "GET",
    path: "/api/interventions/scores",
    pathFields: {},
    queryFields: {},
    sendsBody: false,
    unwrapKey: null,
  },
  get_item: {
    method: "GET",
    path: "/api/items/{id}",
    pathFields: { id: "id" },
    queryFields: {},
    sendsBody: false,
    unwrapKey: "item",
  },
  get_item_artifacts: {
    method: "GET",
    path: "/api/items/{id}/artifacts",
    pathFields: { id: "id" },
    queryFields: {},
    sendsBody: false,
    unwrapKey: null,
  },
  get_item_body: {
    method: "GET",
    path: "/api/items/{id}/body",
    pathFields: { id: "id" },
    queryFields: {},
    sendsBody: false,
    unwrapKey: null,
  },
  get_item_detail: {
    method: "GET",
    path: "/api/items/{id}/detail",
    pathFields: { id: "id" },
    queryFields: {},
    sendsBody: false,
    unwrapKey: "detail",
  },
  get_item_history: {
    method: "GET",
    path: "/api/items/{id}/history",
    pathFields: { id: "id" },
    queryFields: {},
    sendsBody: false,
    unwrapKey: null,
  },
  get_machine: {
    method: "GET",
    path: "/api/machines/{name}",
    pathFields: { name: "name" },
    queryFields: {},
    sendsBody: false,
    unwrapKey: "machine",
  },
  get_needs_you: {
    method: "GET",
    path: "/api/needs-you",
    pathFields: {},
    queryFields: {},
    sendsBody: false,
    unwrapKey: null,
  },
  get_project_detail: {
    method: "GET",
    path: "/api/projects/{id}",
    pathFields: { id: "id" },
    queryFields: {},
    sendsBody: false,
    unwrapKey: "detail",
  },
  get_projects: {
    method: "GET",
    path: "/api/projects",
    pathFields: {},
    queryFields: {},
    sendsBody: false,
    unwrapKey: null,
  },
  get_repo: {
    method: "GET",
    path: "/api/repos/{id}",
    pathFields: { id: "id" },
    queryFields: {},
    sendsBody: false,
    unwrapKey: "repo",
  },
  get_run_scores: {
    method: "GET",
    path: "/api/runs/scores",
    pathFields: {},
    queryFields: {},
    sendsBody: false,
    unwrapKey: null,
  },
  get_session_detail: {
    method: "GET",
    path: "/api/sessions/{id}",
    pathFields: { id: "sessionId" },
    queryFields: {},
    sendsBody: false,
    unwrapKey: null,
  },
  get_session_shape: {
    method: "GET",
    path: "/api/sessions/{id}/shape",
    pathFields: { id: "sessionId" },
    queryFields: {},
    sendsBody: false,
    unwrapKey: null,
  },
  get_setting: {
    method: "GET",
    path: "/api/settings/{key}",
    pathFields: { key: "key" },
    queryFields: {},
    sendsBody: false,
    unwrapKey: null,
  },
  get_settings: {
    method: "GET",
    path: "/api/settings",
    pathFields: {},
    queryFields: {},
    sendsBody: false,
    unwrapKey: null,
  },
  get_stale_candidates: {
    method: "GET",
    path: "/api/stale-candidates",
    pathFields: {},
    queryFields: {},
    sendsBody: false,
    unwrapKey: null,
  },
  heartbeat: {
    method: "POST",
    path: "/api/claims/heartbeat",
    pathFields: {},
    queryFields: {},
    sendsBody: true,
    unwrapKey: "assignment",
  },
  hook_decision: {
    method: "POST",
    path: "/api/hook",
    pathFields: {},
    queryFields: {},
    sendsBody: true,
    unwrapKey: null,
  },
  kill_guard: {
    method: "POST",
    path: "/api/kill-guard",
    pathFields: {},
    queryFields: {},
    sendsBody: true,
    unwrapKey: null,
  },
  list_accounts: {
    method: "GET",
    path: "/api/accounts",
    pathFields: {},
    queryFields: {},
    sendsBody: false,
    unwrapKey: null,
  },
  list_areas: {
    method: "GET",
    path: "/api/areas",
    pathFields: {},
    queryFields: {},
    sendsBody: false,
    unwrapKey: null,
  },
  list_intervention_settings: {
    method: "GET",
    path: "/api/interventions/settings",
    pathFields: {},
    queryFields: {},
    sendsBody: false,
    unwrapKey: null,
  },
  list_items: {
    method: "GET",
    path: "/api/items",
    pathFields: {},
    queryFields: {},
    sendsBody: false,
    unwrapKey: null,
  },
  list_machines: {
    method: "GET",
    path: "/api/machines",
    pathFields: {},
    queryFields: {},
    sendsBody: false,
    unwrapKey: null,
  },
  list_people: {
    method: "GET",
    path: "/api/people",
    pathFields: {},
    queryFields: {},
    sendsBody: false,
    unwrapKey: null,
  },
  list_repos: {
    method: "GET",
    path: "/api/repos",
    pathFields: {},
    queryFields: {},
    sendsBody: false,
    unwrapKey: null,
  },
  list_runs: {
    method: "GET",
    path: "/api/runs",
    pathFields: {},
    queryFields: {},
    sendsBody: false,
    unwrapKey: null,
  },
  loop_add: {
    method: "POST",
    path: "/api/items/{id}/loops",
    pathFields: { id: "itemId" },
    queryFields: {},
    sendsBody: true,
    unwrapKey: null,
  },
  loop_close: {
    method: "POST",
    path: "/api/items/{id}/loops/{loopId}/close",
    pathFields: { id: "itemId", loopId: "loopId" },
    queryFields: {},
    sendsBody: true,
    unwrapKey: "event",
  },
  loop_delete: {
    method: "DELETE",
    path: "/api/items/{id}/loops/{loopId}",
    pathFields: { id: "itemId", loopId: "loopId" },
    queryFields: {},
    sendsBody: true,
    unwrapKey: null,
  },
  loop_edit: {
    method: "PATCH",
    path: "/api/items/{id}/loops/{loopId}",
    pathFields: { id: "itemId", loopId: "loopId" },
    queryFields: {},
    sendsBody: true,
    unwrapKey: null,
  },
  loop_get: {
    method: "GET",
    path: "/api/items/{id}/loops/{loopId}",
    pathFields: { id: "itemId", loopId: "loopId" },
    queryFields: {},
    sendsBody: false,
    unwrapKey: null,
  },
  loop_list: {
    method: "GET",
    path: "/api/items/{id}/loops",
    pathFields: { id: "itemId" },
    queryFields: {},
    sendsBody: false,
    unwrapKey: null,
  },
  mark_event_seen: {
    method: "POST",
    path: "/api/events/{id}/seen",
    pathFields: { id: "eventId" },
    queryFields: {},
    sendsBody: true,
    unwrapKey: null,
  },
  merge_areas: {
    method: "POST",
    path: "/api/areas/merge",
    pathFields: {},
    queryFields: {},
    sendsBody: true,
    unwrapKey: null,
  },
  my_work: {
    method: "GET",
    path: "/api/my-work",
    pathFields: {},
    queryFields: {},
    sendsBody: false,
    unwrapKey: null,
  },
  note: {
    method: "POST",
    path: "/api/items/{id}/notes",
    pathFields: { id: "itemId" },
    queryFields: {},
    sendsBody: true,
    unwrapKey: "event",
  },
  orientation: {
    method: "GET",
    path: "/api/items/{id}/orientation",
    pathFields: { id: "itemId" },
    queryFields: {},
    sendsBody: false,
    unwrapKey: null,
  },
  patch_settings: {
    method: "PATCH",
    path: "/api/settings",
    pathFields: {},
    queryFields: {},
    sendsBody: true,
    unwrapKey: null,
  },
  poll: {
    method: "POST",
    path: "/api/poll",
    pathFields: {},
    queryFields: {},
    sendsBody: true,
    unwrapKey: null,
  },
  progress_report: {
    method: "GET",
    path: "/api/progress-report",
    pathFields: {},
    queryFields: {},
    sendsBody: false,
    unwrapKey: null,
  },
  put_setting: {
    method: "PUT",
    path: "/api/settings/{key}",
    pathFields: { key: "key" },
    queryFields: {},
    sendsBody: true,
    unwrapKey: null,
  },
  readiness: {
    method: "GET",
    path: "/api/ready",
    pathFields: {},
    queryFields: {},
    sendsBody: false,
    unwrapKey: null,
  },
  record_artifact: {
    method: "POST",
    path: "/api/items/{id}/artifacts",
    pathFields: { id: "itemId" },
    queryFields: {},
    sendsBody: true,
    unwrapKey: "artifact",
  },
  record_intervention: {
    method: "POST",
    path: "/api/interventions",
    pathFields: {},
    queryFields: {},
    sendsBody: true,
    unwrapKey: null,
  },
  record_tool_calls: {
    method: "POST",
    path: "/api/tool-calls",
    pathFields: {},
    queryFields: {},
    sendsBody: true,
    unwrapKey: null,
  },
  register_session: {
    method: "POST",
    path: "/api/sessions/{id}/register",
    pathFields: { id: "sessionId" },
    queryFields: {},
    sendsBody: true,
    unwrapKey: "registration",
  },
  release: {
    method: "POST",
    path: "/api/claims/release",
    pathFields: {},
    queryFields: {},
    sendsBody: true,
    unwrapKey: "assignment",
  },
  remove_unrecognised_setting: {
    method: "DELETE",
    path: "/api/settings/unrecognised/{key}",
    pathFields: { key: "key" },
    queryFields: {},
    sendsBody: false,
    unwrapKey: null,
  },
  repair_stuck_projects: {
    method: "POST",
    path: "/api/projects/{id}/repair",
    pathFields: { id: "projectId" },
    queryFields: {},
    sendsBody: true,
    unwrapKey: null,
  },
  reparent_item: {
    method: "POST",
    path: "/api/items/{id}/reparent",
    pathFields: { id: "id" },
    queryFields: {},
    sendsBody: true,
    unwrapKey: "item",
  },
  report_blocked_on_tool: {
    method: "POST",
    path: "/api/items/{id}/blocked-on-tool",
    pathFields: { id: "itemId" },
    queryFields: {},
    sendsBody: true,
    unwrapKey: null,
  },
  request_review: {
    method: "POST",
    path: "/api/items/{id}/review-requests",
    pathFields: { id: "itemId" },
    queryFields: {},
    sendsBody: true,
    unwrapKey: "event",
  },
  restore_item: {
    method: "POST",
    path: "/api/items/{id}/restore",
    pathFields: { id: "id" },
    queryFields: {},
    sendsBody: true,
    unwrapKey: null,
  },
  retype_to_task: {
    method: "POST",
    path: "/api/items/{id}/retype",
    pathFields: { id: "id" },
    queryFields: {},
    sendsBody: true,
    unwrapKey: "item",
  },
  score_intervention: {
    method: "POST",
    path: "/api/interventions/{id}/score",
    pathFields: { id: "eventId" },
    queryFields: {},
    sendsBody: true,
    unwrapKey: null,
  },
  score_run: {
    method: "POST",
    path: "/api/runs/{id}/score",
    pathFields: { id: "runId" },
    queryFields: {},
    sendsBody: true,
    unwrapKey: null,
  },
  search: {
    method: "GET",
    path: "/api/search",
    pathFields: {},
    queryFields: {},
    sendsBody: false,
    unwrapKey: null,
  },
  set_intervention_level: {
    method: "PUT",
    path: "/api/interventions/{id}/level",
    pathFields: { id: "id" },
    queryFields: {},
    sendsBody: true,
    unwrapKey: null,
  },
  sweep: {
    method: "POST",
    path: "/api/sweep",
    pathFields: {},
    queryFields: {},
    sendsBody: true,
    unwrapKey: null,
  },
  takeover: {
    method: "POST",
    path: "/api/claims/takeover",
    pathFields: {},
    queryFields: {},
    sendsBody: true,
    unwrapKey: null,
  },
  transition_item: {
    method: "POST",
    path: "/api/items/{id}/transition",
    pathFields: { id: "id" },
    queryFields: { dryRun: "dry_run" },
    sendsBody: true,
    unwrapKey: null,
  },
  update_account: {
    method: "PATCH",
    path: "/api/accounts/{id}",
    pathFields: { id: "id" },
    queryFields: {},
    sendsBody: true,
    unwrapKey: "account",
  },
  update_area: {
    method: "PATCH",
    path: "/api/areas/{id}",
    pathFields: { id: "id" },
    queryFields: {},
    sendsBody: true,
    unwrapKey: "area",
  },
  update_item: {
    method: "PATCH",
    path: "/api/items/{id}",
    pathFields: { id: "id" },
    queryFields: {},
    sendsBody: true,
    unwrapKey: "item",
  },
  update_machine: {
    method: "PATCH",
    path: "/api/machines/{name}",
    pathFields: { name: "name" },
    queryFields: {},
    sendsBody: true,
    unwrapKey: "machine",
  },
  update_person: {
    method: "PATCH",
    path: "/api/people/{id}",
    pathFields: { id: "id" },
    queryFields: {},
    sendsBody: true,
    unwrapKey: "person",
  },
  update_repo: {
    method: "PATCH",
    path: "/api/repos/{id}",
    pathFields: { id: "id" },
    queryFields: {},
    sendsBody: true,
    unwrapKey: "repo",
  },
  wait_for_crew: {
    method: "GET",
    path: "/api/crew/wait",
    pathFields: {},
    queryFields: {},
    sendsBody: false,
    unwrapKey: null,
  },
});
