// eslint-config-next ships native flat config as of v16 (arrays of flat
// config objects with real plugin references), so it's imported directly
// rather than routed through @eslint/eslintrc's FlatCompat legacy shim —
// that shim expects eslintrc-style shareable configs and chokes on the
// self-referencing plugin objects modern flat configs contain.
import nextCoreWebVitals from "eslint-config-next/core-web-vitals";
import nextTypescript from "eslint-config-next/typescript";

const eslintConfig = [
  ...nextCoreWebVitals,
  ...nextTypescript,
  {
    ignores: [
      "node_modules/**",
      ".next/**",
      "dist/**",
      "coverage/**",
      "src/generated/**",
      // Next-managed, regenerated by `next build`/`next dev` — its header
      // says as much. Once `.next/types` exists it grows a `path`-style
      // triple-slash reference that trips triple-slash-reference regardless.
      "next-env.d.ts",
    ],
  },
];

export default eslintConfig;
