import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    ignores: [
      "node_modules/**",
      ".next/**",
      "dist/**",
      "coverage/**",
      "src/generated/**",
      // Next-managed, regenerated by `next build`/`next dev` — its header
      // says as much. Once `.next/types` exists it grows a `path`-style
      // triple-slash reference that trips triple-slash-reference regardless.
      "next-env.d.ts",
    ],
  },
];

export default eslintConfig;
